import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import styles from '@/styles/global-layout.module.css'
import { Header } from "@/components/main/header";
import { NavbarDesktop } from "@/components/main/navbar/desktop";
import { classnames } from "@/utils/classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classnames(inter.className, styles['global-layout'])}>
        <NavbarDesktop className={styles['row-span-2']}/>
        <Header />
        {children}
      </body>
    </html>
  );
}
